version: "3.9"

services:
  # ðŸšª API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
    networks:
      - microservices-net
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
      - WALLET_SERVICE_URL=http://wallet-service:8002
    env_file:
      - .env
    command: >
      poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # ðŸ”‘ Auth Service
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8001:8001"
    networks:
      - microservices-net
    environment:
      - MONGO_URI=mongodb://mongo:27017
    env_file:
      - .env
    depends_on:
      - mongo
    command: >
      poetry run uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

  # ðŸ§  MongoDB (para el Auth)
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices-net

  # ðŸ’° Wallet Service (Django + Postgres)
  wallet-service:
    # Build wallet-service from its local Dockerfile and tag the image explicitly
    image: wallet-system-wallet-service:dev
    build:
      context: ./wallet-service #forzado de imagen desde la carpeta correcta
      dockerfile: dockerfile #dockerfile en minuscula no reconocida en mayuscula
    container_name: wallet-service
    command: poetry run python manage.py runserver 0.0.0.0:8002
    ports:
      - "8002:8002"
    networks:
      - microservices-net
    env_file:
      - ./wallet-service/.env
    depends_on:
      - wallet-db
    volumes:
      - ./wallet-service:/app

  wallet-db:
    image: postgres:15
    container_name: wallet-db
    environment:
      - POSTGRES_USER=wallet_user
      - POSTGRES_PASSWORD=wallet_pass
      - POSTGRES_DB=wallet_db
    ports:
      - "5544:5432"
    volumes:
      - wallet_db_data:/var/lib/postgresql/data
    networks:
      - microservices-net      

  # ðŸ’¸ Transactions Service (placeholder)
  transactions-service:
    image: nginx:alpine
    container_name: transactions-service
    # Do not start by default; enable with `--profile transactions`
    profiles: ["transactions"]
    networks:
      - microservices-net

networks:
  microservices-net:

volumes:
  mongo_data:
  wallet_db_data:
