services:
  # ðŸšª API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
    networks:
      - microservices-net
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
      - WALLET_SERVICE_URL=http://wallet-service:8002
      - TRANSACTIONS_SERVICE_URL=http://transactions-service:8003
    env_file:
      - .env
    command: >
      poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # ðŸ”‘ Auth Service
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8001:8001"
    networks:
      - microservices-net
    environment:
      - MONGO_URI=mongodb://mongo:27017
    env_file:
      - .env
    depends_on:
      - mongo
      - rabbitmq
    command: >
      poetry run uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

  # ðŸ§  MongoDB (para el Auth)
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices-net

  # ðŸ’° Wallet Service (Django + Postgres)
  wallet-service:
    image: wallet-system-wallet-service:dev
    build:
      context: ./wallet-service
      dockerfile: dockerfile
    container_name: wallet-service
    command:
      - bash
      - start.sh
    ports:
      - "8002:8002"
    networks:
      - microservices-net
    env_file:
      - ./wallet-service/.env
    depends_on:
      - wallet-db
      - rabbitmq
    volumes:
      - ./wallet-service:/app

  wallet-db:
      image: postgres:15
      container_name: wallet-db
      environment:
        - POSTGRES_USER=wallet_user
        - POSTGRES_PASSWORD=wallet_pass_123
        - POSTGRES_DB=wallet_db
      ports:
        - "5544:5432"
      volumes:
        - wallet_db_data:/var/lib/postgresql/data
      networks:
        - microservices-net

  transactions-db:
      image: postgres:15
      container_name: transactions-db
      environment:
        - POSTGRES_USER=trans_user
        - POSTGRES_PASSWORD=trans_pass_123
        - POSTGRES_DB=transactions_db
      ports:
        - "5545:5432"
      volumes:
        - transactions_db_data:/var/lib/postgresql/data
      networks:
        - microservices-net

  # ðŸ’¸ Transactions Service (Django + Postgres)
  transactions-service:
    image: wallet-system-transactions-service:dev
    build:
      context: ./transactions-service
      dockerfile: dockerfile
    container_name: transactions-service
    command:
      - poetry
      - run
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8003
    ports:
      - "8003:8003"
    networks:
      - microservices-net
    env_file:
      - ./transactions-service/.env
    depends_on:
      - transactions-db
      - rabbitmq
    volumes:
      - ./transactions-service:/app

  # ðŸ‡ RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - microservices-net

  # âš™ï¸ Celery Worker (procesa los reintentos)
  auth-worker:
    build: ./auth-service
    container_name: auth-worker
    command: >
      poetry run celery -A task.celery worker --loglevel=info
    depends_on:
      - rabbitmq
      - mongo
    environment:
      - PYTHONPATH=/app
    networks:
      - microservices-net

  # â±ï¸ Celery Beat (programa los reintentos)
  auth-beat:
    build: ./auth-service
    container_name: auth-beat
    command: >
      poetry run celery -A task.celery beat --loglevel=info
    depends_on:
      - rabbitmq
      - mongo
    environment:
      - PYTHONPATH=/app
    networks:
      - microservices-net

  # âš™ï¸ Celery Worker (reintentos de pagos)
  payment-worker:
    build: ./payment-service
    container_name: payment-worker
    command: >
      poetry run celery -A task.celery worker --loglevel=info
    depends_on:
      - rabbitmq
      - mongo
    environment:
      - PYTHONPATH=/app
    networks:
      - microservices-net

  # â±ï¸ Celery Beat (programa los reintentos de pagos)
  payment-beat:
    build: ./payment-service
    container_name: payment-beat
    command: >
      poetry run celery -A task.celery beat --loglevel=info
    depends_on:
      - rabbitmq
      - mongo
    environment:
      - PYTHONPATH=/app
    networks:
      - microservices-net

  payment_service:
    build:
      context: ./payment-service
    container_name: payment_service
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8004
    ports:
      - "8004:8004"
    env_file:
      - ./payment-service/.env
    depends_on:
      - rabbitmq
    networks:
      - microservices-net
    
    

networks:
  microservices-net:

volumes:
  mongo_data:
  wallet_db_data:
  transactions_db_data:
